spring:
  application:
    name: wololo
  profiles:
    active: ${WOLOLO_PROFILE:local}
  flyway:
    connect-retries: 3
    table: flyway_schema_history
    locations: classpath:db/migration
    enabled: true
    user: sa
    password: sa