spring:
  application:
    name: wololo
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
      url: jdbc:h2:file:~/h2/db/wololo.db;AUTO_SERVER=TRUE
      driverClassName: org.h2.Driver
      username: sa
      password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
