spring:
  profiles: local
  h2:
    console:
      enabled: true
  datasource:
      url: jdbc:h2:file:~/h2/db/wololo.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      driverClassName: org.h2.Driver
      username: "sa"
      password: "sa"
      initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect